-- Supabase/PostgreSQL schema. Run this file in Supabase SQL Editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email varchar(190) not null unique,
  password_hash varchar(255) not null,
  role varchar(20) not null default 'staff' check (role in ('admin', 'staff', 'viewer')),
  created_at timestamptz not null default now()
);

create table if not exists public.learners (
  id bigint generated by default as identity primary key,
  lrn varchar(15) not null unique,
  name varchar(150) not null,
  parent_name varchar(150) not null,
  phone varchar(20) not null,
  class_name varchar(100) not null default 'Unassigned',
  qr_version integer not null default 1 check (qr_version > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists learners_set_updated_at on public.learners;
create trigger learners_set_updated_at
before update on public.learners
for each row execute function public.set_updated_at();

create table if not exists public.attendance_logs (
  id bigint generated by default as identity primary key,
  learner_id bigint not null references public.learners(id),
  mode varchar(20) not null check (mode in ('Time IN', 'Time OUT', 'Absent')),
  occurred_at timestamptz not null default now(),
  phone varchar(20) not null,
  sms_status varchar(40) not null default 'Not sent',
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_attendance_occurred_at on public.attendance_logs (occurred_at);
create index if not exists idx_attendance_learner_date on public.attendance_logs (learner_id, occurred_at);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  action varchar(100) not null,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_created_at on public.audit_logs (created_at);

alter table public.users enable row level security;
alter table public.learners enable row level security;
alter table public.attendance_logs enable row level security;
alter table public.audit_logs enable row level security;
